Repository ory/kratos, pull requests merged in 2020-10, with the labels that each got.

#708 fix: mark flow methods' fields as required
  .schema/api.swagger.json
  internal/httpclient/models/recovery_flow_method.go
  internal/httpclient/models/registration_flow_method.go
  internal/httpclient/models/settings_flow_method.go
  internal/httpclient/models/verification_flow_method.go
  selfservice/flow/recovery/flow_method.go
  selfservice/flow/registration/flow_method.go
  selfservice/flow/settings/flow_method.go
  selfservice/flow/verification/flow_method.go
  selfservice/strategy/oidc/strategy_settings_test.go
Labels: bug, corp/m2

#519 feat: GitLab OIDC Provider
  .schema/config.schema.json
  docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx
  docs/docs/self-service/flows/user-login.mdx
  docs/docs/self-service/flows/user-registration.mdx
  selfservice/strategy/oidc/provider_config.go
  selfservice/strategy/oidc/provider_gitlab.go
Labels: stale

#796 fix: force brew install statement
  .goreleaser.yml
Labels: bug, ci, corp/m3
