Repository ory/kratos, pull requests merged in 2021-06, with the labels that each got.

#1421 test(e2e): greatly improve test performance
  package-lock.json
  package.json
  test/e2e/.gitignore
  test/e2e/cypress/integration/profiles/email/login/error.spec.js
  test/e2e/cypress/integration/profiles/email/login/success.spec.js
  test/e2e/cypress/integration/profiles/email/login/ui.spec.js
  test/e2e/cypress/integration/profiles/email/logout/success.spec.js
  test/e2e/cypress/integration/profiles/email/registration/errors.spec.js
  test/e2e/cypress/integration/profiles/email/registration/success.spec.js
  test/e2e/cypress/integration/profiles/email/registration/ui.spec.js
  test/e2e/cypress/integration/profiles/email/settings/errors.spec.js
  test/e2e/cypress/integration/profiles/email/settings/success.spec.js
  test/e2e/cypress/integration/profiles/email/settings/ui.spec.js
  test/e2e/cypress/integration/profiles/mobile/login/errors.spec.js
  test/e2e/cypress/integration/profiles/mobile/login/success.spec.js
  test/e2e/cypress/integration/profiles/mobile/registration/errors.spec.js
  test/e2e/cypress/integration/profiles/mobile/registration/success.spec.js
  test/e2e/cypress/integration/profiles/mobile/settings/errors.spec.js
  test/e2e/cypress/integration/profiles/mobile/settings/success.spec.js
  test/e2e/cypress/integration/profiles/oidc/login/error.spec.js
  test/e2e/cypress/integration/profiles/oidc/login/success.spec.js
  test/e2e/cypress/integration/profiles/oidc/logout/success.spec.js
  test/e2e/cypress/integration/profiles/oidc/registration/error.spec.js
  test/e2e/cypress/integration/profiles/oidc/registration/success.spec.js
  test/e2e/cypress/integration/profiles/oidc/settings/error.spec.js
  test/e2e/cypress/integration/profiles/oidc/settings/success.spec.js
  test/e2e/cypress/integration/profiles/recovery/recovery/errors.spec.js
  test/e2e/cypress/integration/profiles/recovery/recovery/success.spec.js
  test/e2e/cypress/integration/profiles/recovery/settings/success.spec.js
  test/e2e/cypress/integration/profiles/verification/registration/errors.spec.js
  test/e2e/cypress/integration/profiles/verification/registration/success.spec.js
  test/e2e/cypress/integration/profiles/verification/settings/error.spec.js
  test/e2e/cypress/integration/profiles/verification/settings/success.spec.js
  test/e2e/cypress/integration/profiles/verification/verify/errors.spec.js
  test/e2e/cypress/integration/profiles/verification/verify/success.spec.js
  test/e2e/cypress/support/commands.js
  test/e2e/run.sh
Labels: tests

#1352 feat: OIDC provider for Auth0.com Tenants.
  docs/docs/guides/sign-in-with-github-google-facebook-linkedin.mdx
  driver/config/.schema/config.schema.json
  selfservice/strategy/oidc/provider_auth0.go
  selfservice/strategy/oidc/provider_config.go
Labels: pending reply

#1428 fix: deprecate sessionCookie
  .schema/openapi/patches/meta.yaml
  internal/httpclient/README.md
  internal/httpclient/api/openapi.yaml
  spec/openapi.json
  spec/swagger.json
  swagger_meta.go
Labels: bug

#1430 fix: use STARTTLS for smtps connections
  courier/courier.go
  test/e2e/profiles/kratos.base.yml
Labels: bug

#1431 fix: incorrect openapi specification for verification submission
  docs/docs/self-service.mdx
  examples/go/pkg/common.go
  examples/go/submit/verification/main.go
  examples/go/submit/verification/main_test.go
  internal/httpclient/.openapi-generator/FILES
  internal/httpclient/README.md
  internal/httpclient/api/openapi.yaml
  internal/httpclient/api_public.go
  internal/httpclient/docs/PublicApi.md
  internal/httpclient/docs/SubmitSelfServiceRecoveryFlowBody.md
  internal/httpclient/docs/SubmitSelfServiceVerificationFlowBody.md
  internal/httpclient/model_submit_self_service_recovery_flow_body.go
  internal/httpclient/model_submit_self_service_verification_flow_body.go
  selfservice/flow/recovery/handler.go
  selfservice/flow/verification/handler.go
  spec/openapi.json
  spec/swagger.json
Labels: bug

#1458 feat: anti-CSRF measures when fetching flows
  CHANGELOG.md
  docs/docs/CHANGELOG.md
  docs/package-lock.json
  examples/go/pkg/common.go
  internal/httpclient/README.md
  internal/httpclient/api/openapi.yaml
  internal/httpclient/api_admin.go
  internal/httpclient/api_public.go
  internal/httpclient/docs/AdminApi.md
  internal/httpclient/docs/PublicApi.md
  internal/testhelpers/selfservice_settings.go
  package-lock.json
  package.json
  selfservice/flow/login/error_test.go
  selfservice/flow/login/handler.go
  selfservice/flow/login/handler_test.go
  selfservice/flow/logout/handler.go
  selfservice/flow/logout/handler_test.go
  selfservice/flow/recovery/error_test.go
  selfservice/flow/recovery/handler.go
  selfservice/flow/recovery/handler_test.go
  selfservice/flow/registration/error_test.go
  selfservice/flow/registration/handler.go
  selfservice/flow/registration/handler_test.go
  selfservice/flow/request.go
  selfservice/flow/request_test.go
  selfservice/flow/settings/error_test.go
  selfservice/flow/settings/handler.go
  selfservice/flow/settings/handler_test.go
  selfservice/flow/verification/error_test.go
  selfservice/flow/verification/handler.go
  selfservice/flow/verification/handler_test.go
  selfservice/strategy/link/strategy_recovery.go
  selfservice/strategy/link/strategy_recovery_test.go
  selfservice/strategy/link/strategy_verification.go
  selfservice/strategy/link/strategy_verification_test.go
  selfservice/strategy/oidc/strategy_settings_test.go
  selfservice/strategy/password/login.go
  selfservice/strategy/password/registration.go
  selfservice/strategy/password/settings.go
  selfservice/strategy/password/settings_test.go
  selfservice/strategy/profile/strategy.go
  selfservice/strategy/profile/strategy_test.go
  spec/openapi.json
  spec/swagger.json
  test/e2e/cypress/integration/profiles/email/login/error.spec.js
  test/e2e/cypress/integration/profiles/email/registration/errors.spec.js
  test/e2e/cypress/integration/profiles/email/settings/errors.spec.js
  x/nosurf.go
  x/nosurf_test.go
Labels: feat
